package phonesimulator;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sushilthe
 */
public class Phonesimulator extends javax.swing.JPanel {

    /**
     * Creates new form Phonesimulator
     */
    JFrame frame;
    boolean call_1 = true;
    boolean call_2 = true;
    boolean call_3 = true;
    boolean call_4 = true;
    boolean call_5 = true;
    boolean call_6 = true;
    int calling[] = new int[7];
    int total_call = 0;
    int success_call = 0;
    int failed_call = 0;
    
    public Phonesimulator(JFrame frame){
        this.frame = frame;
        initComponents();
    }
    
    private static void createAndShowGUI() {
        //Create and set up the window.
        JFrame frame = new JFrame("Phone Call Simulator");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create and set up the content pane.
        Phonesimulator newContentPane = new Phonesimulator(frame);
        newContentPane.setOpaque(true); //content panes must be opaque
        frame.setContentPane(newContentPane);

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }
    
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        call1 = new javax.swing.JButton();
        end1 = new javax.swing.JButton();
        call2 = new javax.swing.JButton();
        end2 = new javax.swing.JButton();
        call3 = new javax.swing.JButton();
        end3 = new javax.swing.JButton();
        call4 = new javax.swing.JButton();
        end4 = new javax.swing.JButton();
        call5 = new javax.swing.JButton();
        end5 = new javax.swing.JButton();
        call6 = new javax.swing.JButton();
        end6 = new javax.swing.JButton();
        phone1 = new javax.swing.JLabel();
        phone2 = new javax.swing.JLabel();
        phone3 = new javax.swing.JLabel();
        phone4 = new javax.swing.JLabel();
        phone5 = new javax.swing.JLabel();
        phone6 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        status3 = new javax.swing.JLabel();
        status4 = new javax.swing.JLabel();
        status5 = new javax.swing.JLabel();
        status6 = new javax.swing.JLabel();
        totalsuccessllabel = new javax.swing.JLabel();
        totalfailedllabel = new javax.swing.JLabel();
        totalcallsllabel = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setName("mainpanel"); // NOI18N

        call1.setText("Call");
        call1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call1ActionPerformed(evt);
            }
        });

        end1.setText("End");
        end1.setEnabled(false);
        end1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end1ActionPerformed(evt);
            }
        });

        call2.setText("Call");
        call2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call2ActionPerformed(evt);
            }
        });

        end2.setText("End");
        end2.setEnabled(false);
        end2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end2ActionPerformed(evt);
            }
        });

        call3.setText("Call");
        call3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call3ActionPerformed(evt);
            }
        });

        end3.setText("End");
        end3.setEnabled(false);
        end3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end3ActionPerformed(evt);
            }
        });

        call4.setText("Call");
        call4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call4ActionPerformed(evt);
            }
        });

        end4.setText("End");
        end4.setEnabled(false);
        end4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end4ActionPerformed(evt);
            }
        });

        call5.setText("Call");
        call5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call5ActionPerformed(evt);
            }
        });

        end5.setText("End");
        end5.setEnabled(false);
        end5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end5ActionPerformed(evt);
            }
        });

        call6.setText("Call");
        call6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call6ActionPerformed(evt);
            }
        });

        end6.setText("End");
        end6.setEnabled(false);
        end6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end6ActionPerformed(evt);
            }
        });

        phone1.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone1.setText("1");

        phone2.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone2.setText("2");

        phone3.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone3.setText("3");

        phone4.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone4.setText("4");

        phone5.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone5.setText("5");

        phone6.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone6.setText("6");

        status1.setText("Ready");

        status2.setText("Ready");

        status3.setText("Ready");

        status4.setText("Ready");

        status5.setText("Ready");

        status6.setText("Ready");

        totalsuccessllabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 18)); // NOI18N
        totalsuccessllabel.setText("Total Successful Calls:");

        totalfailedllabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 18)); // NOI18N
        totalfailedllabel.setText("Total Failed Calls:");

        totalcallsllabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 18)); // NOI18N
        totalcallsllabel.setText("Total Calls:");

        success.setFont(new java.awt.Font("Open Sans Extrabold", 0, 18)); // NOI18N
        success.setText("0");

        fail.setFont(new java.awt.Font("Open Sans Extrabold", 0, 18)); // NOI18N
        fail.setText("0");

        total.setFont(new java.awt.Font("Open Sans Extrabold", 0, 18)); // NOI18N
        total.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(status4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(call1)
                                            .addComponent(end1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phone1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phone4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(call3)
                                                    .addComponent(end3))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(totalfailedllabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(fail))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 188, Short.MAX_VALUE)
                                                                .addComponent(totalcallsllabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(total))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(phone3)
                                                                .addGap(0, 0, Short.MAX_VALUE))))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(call2)
                                                            .addComponent(end2))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(phone2))
                                                    .addComponent(status2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(totalsuccessllabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(success)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phone5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(phone6)
                                                .addGap(1, 1, 1)))))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(status3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(call5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(end5))
                                    .addComponent(call4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(end4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(call6)
                                    .addComponent(status5)
                                    .addComponent(end6)
                                    .addComponent(status6))
                                .addGap(1, 1, 1)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(call4)
                            .addComponent(call1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(end1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phone1)
                        .addComponent(phone4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status1)
                    .addComponent(status4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(call2)
                            .addComponent(call5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end2)
                            .addComponent(end5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phone2)
                        .addComponent(totalsuccessllabel)
                        .addComponent(success)
                        .addComponent(phone5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalfailedllabel)
                                .addComponent(fail)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total)
                            .addComponent(totalcallsllabel))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phone6)
                                .addComponent(phone3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(call3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(end3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(status5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(call6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status6)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void call1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call1ActionPerformed
        Object possibilities[] = {"2", "3", "4", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "2");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call2.setEnabled(false);
                end2.setEnabled(true);
                call_1= false;
                call_2 = false;
                calling[1] = 2;
                calling[2] = 1;
                status1.setText("In call with 2");
                status2.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_1= false;
                call_3 = false;
                calling[1] = 3;
                calling[3] = 1;
                status1.setText("In call with 3");
                status3.setText("In call with 1");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_1= false;
                call_4 = false;
                calling[1] = 4;
                calling[4] = 1;
                status1.setText("In call with 4");
                status4.setText("In call with 1");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_1= false;
                call_5 = false;
                calling[1] = 5;
                calling[5] = 1;
                status1.setText("In call with 5");
                status5.setText("In call with 1");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_1= false;
                call_6 = false;
                calling[1] = 6;
                calling[6] = 1;
                status1.setText("In call with 6");
                status6.setText("In call with 1");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.                  
    }//GEN-LAST:event_call1ActionPerformed

    private void end1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end1ActionPerformed
        call1.setEnabled(true);
        end1.setEnabled(false);
        status1.setText("Ready");
        call_1 = true;
        if(calling[1] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[1] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[1] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[1] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[1] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end1ActionPerformed

    private void call2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call2ActionPerformed
        Object possibilities[] = {"1", "3", "4", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_2= false;
                call_1 = false;
                calling[2] = 1;
                calling[1] = 2;
                status1.setText("In call with 2");
                status2.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_2= false;
                call_3 = false;
                calling[2] = 3;
                calling[3] = 2;
                status2.setText("In call with 3");
                status3.setText("In call with 2");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_2= false;
                call_4 = false;
                calling[2] = 4;
                calling[4] = 2;
                status2.setText("In call with 4");
                status4.setText("In call with 2");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_2= false;
                call_5 = false;
                calling[2] = 5;
                calling[5] = 2;
                status2.setText("In call with 5");
                status5.setText("In call with 2");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_2= false;
                call_6 = false;
                calling[2] = 6;
                calling[6] = 2;
                status2.setText("In call with 6");
                status6.setText("In call with 2");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call2ActionPerformed

    private void end2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end2ActionPerformed
        call2.setEnabled(true);
        end2.setEnabled(false);
        status2.setText("Ready");
        call_2 = true;
        if(calling[2] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[2] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[2] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[2] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[2] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end2ActionPerformed

    private void call3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call3ActionPerformed
        Object possibilities[] = {"1", "2", "4", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_3= false;
                call_1 = false;
                calling[3] = 1;
                calling[1] = 3;
                status1.setText("In call with 3");
                status3.setText("In call with 1");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_2= false;
                call_3 = false;
                calling[2] = 3;
                calling[3] = 2;
                status2.setText("In call with 3");
                status3.setText("In call with 2");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_3= false;
                call_4 = false;
                calling[3] = 4;
                calling[4] = 3;
                status3.setText("In call with 4");
                status4.setText("In call with 3");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_3= false;
                call_5 = false;
                calling[3] = 5;
                calling[5] = 3;
                status3.setText("In call with 5");
                status5.setText("In call with 3");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_3= false;
                call_6 = false;
                calling[3] = 6;
                calling[6] = 3;
                status3.setText("In call with 6");
                status6.setText("In call with 3");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call3ActionPerformed

    private void end3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end3ActionPerformed
        call3.setEnabled(true);
        end3.setEnabled(false);
        status3.setText("Ready");
        call_3 = true;
        if(calling[3] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[3] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[3] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[3] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[3] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end3ActionPerformed

    private void call4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call4ActionPerformed
        Object possibilities[] = {"1", "2", "3", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_4= false;
                call_1 = false;
                calling[4] = 1;
                calling[1] = 4;
                status1.setText("In call with 4");
                status4.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_4= false;
                call_3 = false;
                calling[4] = 3;
                calling[3] = 4;
                status4.setText("In call with 3");
                status3.setText("In call with 4");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_2= false;
                call_4 = false;
                calling[2] = 4;
                calling[4] = 2;
                status2.setText("In call with 4");
                status4.setText("In call with 2");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_4= false;
                call_5 = false;
                calling[4] = 5;
                calling[5] = 4;
                status4.setText("In call with 5");
                status5.setText("In call with 4");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_4= false;
                call_6 = false;
                calling[4] = 6;
                calling[6] = 4;
                status4.setText("In call with 6");
                status6.setText("In call with 4");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call4ActionPerformed

    private void end4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end4ActionPerformed
        call4.setEnabled(true);
        end4.setEnabled(false);
        status4.setText("Ready");
        call_4 = true;
        if(calling[4] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[4] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[4] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[4] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[4] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end4ActionPerformed

    private void call5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call5ActionPerformed
        Object possibilities[] = {"1", "2", "3", "4", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_5= false;
                call_1 = false;
                calling[5] = 1;
                calling[1] = 5;
                status1.setText("In call with 5");
                status5.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_5= false;
                call_3 = false;
                calling[5] = 3;
                calling[3] = 5;
                status5.setText("In call with 3");
                status3.setText("In call with 5");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_5= false;
                call_4 = false;
                calling[5] = 4;
                calling[4] = 5;
                status5.setText("In call with 4");
                status4.setText("In call with 5");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_2= false;
                call_5 = false;
                calling[2] = 5;
                calling[5] = 2;
                status2.setText("In call with 5");
                status5.setText("In call with 2");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_5= false;
                call_6 = false;
                calling[5] = 6;
                calling[6] = 5;
                status5.setText("In call with 6");
                status6.setText("In call with 5");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call5ActionPerformed

    private void end5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end5ActionPerformed
        call5.setEnabled(true);
        end5.setEnabled(false);
        status5.setText("Ready");
        call_5 = true;
        if(calling[5] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[5] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[5] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[5] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[5] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end5ActionPerformed

    private void call6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call6ActionPerformed
        Object possibilities[] = {"1", "2", "3", "4", "5"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_6= false;
                call_1 = false;
                calling[6] = 1;
                calling[1] = 6;
                status1.setText("In call with 6");
                status6.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_6= false;
                call_3 = false;
                calling[6] = 3;
                calling[3] = 6;
                status6.setText("In call with 3");
                status3.setText("In call with 6");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_6= false;
                call_4 = false;
                calling[6] = 4;
                calling[4] = 6;
                status6.setText("In call with 4");
                status4.setText("In call with 6");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_6= false;
                call_5 = false;
                calling[6] = 5;
                calling[5] = 6;
                status6.setText("In call with 5");
                status5.setText("In call with 6");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_2= false;
                call_6 = false;
                calling[2] = 6;
                calling[6] = 2;
                status2.setText("In call with 6");
                status6.setText("In call with 2");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call6ActionPerformed

    private void end6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end6ActionPerformed
        call6.setEnabled(true);
        end6.setEnabled(false);
        status6.setText("Ready");
        call_6 = true;
        if(calling[6] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[6] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[6] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[6] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[6] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }
    }//GEN-LAST:event_end6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton call1;
    private javax.swing.JButton call2;
    private javax.swing.JButton call3;
    private javax.swing.JButton call4;
    private javax.swing.JButton call5;
    private javax.swing.JButton call6;
    private javax.swing.JButton end1;
    private javax.swing.JButton end2;
    private javax.swing.JButton end3;
    private javax.swing.JButton end4;
    private javax.swing.JButton end5;
    private javax.swing.JButton end6;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone2;
    private javax.swing.JLabel phone3;
    private javax.swing.JLabel phone4;
    private javax.swing.JLabel phone5;
    private javax.swing.JLabel phone6;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status4;
    private javax.swing.JLabel status5;
    private javax.swing.JLabel status6;
    private javax.swing.JLabel success;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalcallsllabel;
    private javax.swing.JLabel totalfailedllabel;
    private javax.swing.JLabel totalsuccessllabel;
    // End of variables declaration//GEN-END:variables
}
